// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "An API for generating wordchains",
    "title": "WordChains",
    "contact": {
      "name": "SuperOrbital",
      "url": "http://superorbital.io/",
      "email": "info@superorbital.io"
    },
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/v1/random": {
      "post": {
        "description": "Generate a wordchain",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "wordchain"
        ],
        "summary": "Get a wordchain",
        "operationId": "get-random",
        "parameters": [
          {
            "description": "Wordchain Parameters",
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/models.WordchainPrefs"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "string"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "models.WordchainPrefs": {
      "type": "object",
      "properties": {
        "divider": {
          "description": "The divider to use between each chain segment.",
          "type": "string"
        },
        "length": {
          "description": "The length of the words for each chain segment.",
          "type": "integer"
        },
        "postpend": {
          "description": "A string to postpend the chain segment with.",
          "type": "string"
        },
        "prepend": {
          "description": "A string to prepend the chain segment with.",
          "type": "string"
        },
        "seed": {
          "description": "A string to use as a seed for deterministic results.",
          "type": "string"
        },
        "type": {
          "description": "An array of word types to return in the chain.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "An API for generating wordchains",
    "title": "WordChains",
    "contact": {
      "name": "SuperOrbital",
      "url": "http://superorbital.io/",
      "email": "info@superorbital.io"
    },
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/v1/random": {
      "post": {
        "description": "Generate a wordchain",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "wordchain"
        ],
        "summary": "Get a wordchain",
        "operationId": "get-random",
        "parameters": [
          {
            "description": "Wordchain Parameters",
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/models.WordchainPrefs"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "string"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "models.WordchainPrefs": {
      "type": "object",
      "properties": {
        "divider": {
          "description": "The divider to use between each chain segment.",
          "type": "string"
        },
        "length": {
          "description": "The length of the words for each chain segment.",
          "type": "integer"
        },
        "postpend": {
          "description": "A string to postpend the chain segment with.",
          "type": "string"
        },
        "prepend": {
          "description": "A string to prepend the chain segment with.",
          "type": "string"
        },
        "seed": {
          "description": "A string to use as a seed for deterministic results.",
          "type": "string"
        },
        "type": {
          "description": "An array of word types to return in the chain.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}`))
}
