// Code generated by go-swagger; DO NOT EDIT.

package wordchain

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/superorbital/wordchain/models"
)

// GetRandomOKCode is the HTTP code returned for type GetRandomOK
const GetRandomOKCode int = 200

/*GetRandomOK OK

swagger:response getRandomOK
*/
type GetRandomOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetRandomOK creates GetRandomOK with default headers values
func NewGetRandomOK() *GetRandomOK {

	return &GetRandomOK{}
}

// WithPayload adds the payload to the get random o k response
func (o *GetRandomOK) WithPayload(payload string) *GetRandomOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get random o k response
func (o *GetRandomOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRandomOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetRandomBadRequestCode is the HTTP code returned for type GetRandomBadRequest
const GetRandomBadRequestCode int = 400

/*GetRandomBadRequest Bad Request

swagger:response getRandomBadRequest
*/
type GetRandomBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetRandomBadRequest creates GetRandomBadRequest with default headers values
func NewGetRandomBadRequest() *GetRandomBadRequest {

	return &GetRandomBadRequest{}
}

// WithPayload adds the payload to the get random bad request response
func (o *GetRandomBadRequest) WithPayload(payload string) *GetRandomBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get random bad request response
func (o *GetRandomBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRandomBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetRandomDefault generic error response

swagger:response getRandomDefault
*/
type GetRandomDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetRandomDefault creates GetRandomDefault with default headers values
func NewGetRandomDefault(code int) *GetRandomDefault {
	if code <= 0 {
		code = 500
	}

	return &GetRandomDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get random default response
func (o *GetRandomDefault) WithStatusCode(code int) *GetRandomDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get random default response
func (o *GetRandomDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get random default response
func (o *GetRandomDefault) WithPayload(payload *models.Error) *GetRandomDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get random default response
func (o *GetRandomDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRandomDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
