name: Build Container Image

on:
  push:
    branches: 
      - 'main'

jobs:
  buildx:
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read 
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: superorbital/wordchain:latest
      - uses: sigstore/cosign-installer@main
      - name: Cosign signature
        run: COSIGN_EXPERIMENTAL=1 cosign sign -a git_sha=$GITHUB_SHA docker.io/superorbital/wordchain:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

